### ISSUE TITLE
Do not preserve markup of elements with the `property` attribute and without markup preserving `datatype`

### ISSUE THREAD

**Issue by csarven** [rubensworks/rdfa-streaming-parser.js#49]
Elements with the `property` attribute and without the `datatype` attribute, `datatype=""`, `datatype="rdf:HTML"`, or `datatype="rdf:XMLLiteral"` should not have the parser preserve the markup in the content of the element and add all namespaces and prefixes.

For example, given input:

```html
<dd about="#foo" property="skos:definition">foo <em>bar</em> baz</dd>
```

the following is given:

```turtle
<#foo> skos:definition "foo <em xmlns=\"http://www.w3.org/1999/xhtml\".......\">bar</em> baz" .
```

but the expected RDF is:

```turtle
<#foo> skos:definition "foo bar baz" .
```

**Comment by rubensworks** [comment]
It's been a while since I looked into the processing model of RDFa.
But do you mean that the markup should not be preserved without the `datatype` attribute or `datatype=""`, but it must be preserved when using `datatype="rdf:HTML"` or `datatype="rdf:XMLLiteral"`?

**Comment by csarven** [comment]
That's right AFAICT.

Doublechecking.. Some cases appear to give the expected output but some others do not, i.e., markup is preserved. For example, see https://solidproject.org/ED/protocol 's `skos:definition` values.

**Comment by csarven** [comment]
Nudge. It'd be great to fix this. We're trying to commit to using this parser now in dokieli but this issue is kind of a blocker.

Without this fix, I think the consuming applications would probably have to convert the literal to a DOM object and get its `.textContent` or something to get the actual literal, and that's quite cumbersome.

FWIW, compare:

https://rdf-play.rubensworks.net/#url=https%3A%2F%2Fsolidproject.org%2FTR%2Fprotocol

with

http://rdf.greggkellogg.net/distiller?command=serialize&url=https:%2F%2Fsolidproject.org%2FTR%2Fnotifications-protocol&raw

**Comment by rubensworks** [comment]
Should be fixed in 3.0.1.

It might take a while for it to propagate to rdf-play though.

**Comment by csarven** [comment]
Great! Thank you. Did a preliminary test in dokieli and seems to be working as intended. Will keep you posted if I spot any issues.

**Comment by csarven** [comment]
Could you please verify this is deployed / working as expected at rdf-play? I think I'm still seeing the bug behaviour. Another example:

```html
<https://solidproject.org/TR/protocol#Client> a <http://www.w3.org/2004/02/skos/core#Concept>;
    <http://www.w3.org/2004/02/skos/core#prefLabel> "<dfn id=\"Client\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:as=\"https://www.w3.org/ns/activitystreams#\" xmlns:cito=\"http://purl.org/spar/cito/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:doap=\"http://usefulinc.com/ns/doap#\" xmlns:earl=\"http://www.w3.org/ns/earl#\" xmlns:ldp=\"http://www.w3.org/ns/ldp#\" xmlns:mem=\"http://mementoweb.org/ns#\" xmlns:odrl=\"http://www.w3.org/ns/odrl/2/\" xmlns:owl=\"http://www.w3.org/2002/07/owl#\" xmlns:prov=\"http://www.w3.org/ns/prov#\" xmlns:qb=\"http://purl.org/linked-data/cube#\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\" xmlns:rel=\"https://www.w3.org/ns/iana/link-relations/relation#\" xmlns:schema=\"http://schema.org/\" xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\" xmlns:spec=\"http://www.w3.org/ns/spec#\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"><a class=\"self-link\" href=\"#Client\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:as=\"https://www.w3.org/ns/activitystreams#\" xmlns:cito=\"http://purl.org/spar/cito/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:doap=\"http://usefulinc.com/ns/doap#\" xmlns:earl=\"http://www.w3.org/ns/earl#\" xmlns:ldp=\"http://www.w3.org/ns/ldp#\" xmlns:mem=\"http://mementoweb.org/ns#\" xmlns:odrl=\"http://www.w3.org/ns/odrl/2/\" xmlns:owl=\"http://www.w3.org/2002/07/owl#\" xmlns:prov=\"http://www.w3.org/ns/prov#\" xmlns:qb=\"http://purl.org/linked-data/cube#\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\" xmlns:rel=\"https://www.w3.org/ns/iana/link-relations/relation#\" xmlns:schema=\"http://schema.org/\" xmlns:skos=\"http://www.w3.org/2004/02/skos/core#\" xmlns:spec=\"http://www.w3.org/ns/spec#\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"></a>Client</dfn>"@en;
```

Expected: `skos:prefLabel "Client"@en`.

Dokieli is using `"rdfa-streaming-parser": "^3.0.1"` and it appears to be working as expected as mentioned before.

**Comment by rubensworks** [comment]
rdf-play is [not using the latest version](https://github.com/rubensworks/rdf-play.js/blob/master/yarn.lock#L3349) indeed.
It should auto-update once I publish a new release of rdf-dereference.

**Comment by csarven** [comment]
Right! Will this help towards fixing that https://github.com/comunica/comunica/pull/1624 ?
